### ISSUE TITLE
[데이터] 모든 Entity들에 대한 대량의 데이터 삽입

### ISSUE THREAD

**Issue by PreAgile** [f-lab-edu/market-early#5]
상품, 유저, 주문 등등 각 Entity마다 대량의 데이터들을 삽입해야 테스트하기 용이

- [x] 상품 데이터 삽입
- [x] 유저 데이터 삽입
- [x] 주문 데이터 삽입
- [x] 장바구니 데이터 삽입

**Comment by PreAgile** [comment]
Mock Data는 Code를 chatGPT나 기타 다른 생성형AI에 입력해서 데이터를 생성하게 만들어서 SQL로 Insert 하는게 좋을것같다.

**Comment by kee1993** [comment]
네 이렇게 아니면 java 코드로 하셔도되요 (스크립트처럼 작성하셔서)
