### ISSUE TITLE
[유저] Securiy 관련 설정

### ISSUE THREAD

**Issue by PreAgile** [f-lab-edu/market-early#7]
유저 로그인시 관리 방법으로는 세션관리와 jwt web token으로 관리하는 방법이 있습니다. 둘중에 어떤걸 할지 고민중인데 각각 알아보면

세션 관리는 서버의 메모리에서 데이터를 불러와서 관리하고 나름 구현은 간단하나 모바일 클라이언트까지 고려하거나 여러 서버를 사용한다고하면 서버에 대한 부하와 모바일 클라이언트에 대한 적용이 어려움, 멀티 서버로 구현시 싱크를 맞추기위해 캐시나 데이터베이스를 통해 저장후 불러와야하기때문에 복잡성 및 부하가 심해질수도있음

Jwt Token으로 하면 모바일이나 웹 클라이언트에 대해 동일하게 적용할수있고 나중에 여러개의 서버로 구현할때도 싱크를 맞추기 쉽다.
단점으로는 토큰을 관리해줘야된다는것과 탈취에 대한 위험성 , 보안에 대한 위험성이 있는것같습니다.

이외에 더 고려해볼만한 사항, 혹은 구현해야할때 고려해야할점이 무엇이며 어떤걸 구현하는편이 좋을까요?

-> Jwt Token으로 인증 방식 구현결정

- [x] Jwt Token 으로 인증방식구현

**Comment by kee1993** [comment]
이경우는 솔직히 요즘 트렌드로는 jwt token이좋아요.

근데 세션관리 경험을 해보고싶으면 전자도좋습니다
